# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-20 21:18
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(default='', help_text='环境名称', max_length=10, verbose_name='环境名称')),
                ('env_desc', models.TextField(help_text='环境描述', verbose_name='环境描述')),
                ('env_type', models.IntegerField(choices=[(1, '开发环境'), (2, '测试环境'), (3, '预生产环境'), (4, '生产环境')], default=1, help_text='环境类型', verbose_name='环境类型')),
                ('host', models.CharField(default='', help_text='IP/域名', max_length=30, verbose_name='IP/域名')),
                ('port', models.IntegerField(default=8080, help_text='端口', verbose_name='端口')),
                ('env_status', models.IntegerField(choices=[(0, '禁用'), (1, '可用')], default=1, help_text='环境是否可用', verbose_name='环境是否可用')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('env_info', DjangoUeditor.models.UEditorField(verbose_name='环境信息')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
            },
        ),
        migrations.CreateModel(
            name='ModelManager',
            fields=[
                ('id', models.AutoField(help_text='模块id', max_length=16, primary_key=True, serialize=False, verbose_name='模块id')),
                ('model_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='模块名称')),
                ('parent_name', models.CharField(blank=True, default='', help_text='父模块名称', max_length=20, null=True, verbose_name='父模块名称')),
                ('parent_id', models.IntegerField(default=1, help_text='父模块id', verbose_name='父模块id')),
                ('models_desc', models.TextField(help_text='模块描述', verbose_name='模块描述')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(help_text='项目id', max_length=16, primary_key=True, serialize=False, verbose_name='项目id')),
                ('project_name', models.CharField(default='', help_text='项目名称', max_length=20, verbose_name='项目名称')),
                ('project_desc', models.TextField(default='', help_text='项目描述', verbose_name='项目描述')),
                ('open_time', models.DateField(blank=True, default=datetime.datetime.now, help_text='项目开始日期', null=True, verbose_name='项目开始日期')),
                ('close_time', models.DateField(blank=True, default=datetime.datetime.now, help_text='项目结束日期', null=True, verbose_name='项目结束日期')),
                ('members', models.CharField(blank=True, default='', help_text='项目成员', max_length=100, null=True, verbose_name='项目成员')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.AddField(
            model_name='modelmanager',
            name='project',
            field=models.ForeignKey(help_text='项目名称', on_delete=django.db.models.deletion.CASCADE, to='base_config.ProjectManager', verbose_name='项目名称'),
        ),
    ]
