# Generated by Django 2.2.17 on 2020-11-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseapi',
            name='execution_sequence',
            field=models.SmallIntegerField(default=0, verbose_name='接口执行顺序'),
        ),
    ]
