# Generated by Django 2.2.17 on 2020-11-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseapi_execution_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiparams',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paramars', to='cases.ApiManagerment', verbose_name='所属接口'),
        ),
        migrations.AlterField(
            model_name='caseapiresponse',
            name='case_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_case_api', to='cases.CaseApi', verbose_name='所属接口'),
        ),
        migrations.AlterField(
            model_name='casestepparams',
            name='case_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_paramars', to='cases.CaseApi', verbose_name='所属接口'),
        ),
    ]
