# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-09 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200708_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseapi',
            name='actual_data',
            field=models.TextField(blank=True, default='', null=True, verbose_name='实际结果'),
        ),
        migrations.AddField(
            model_name='caseapi',
            name='extract_result',
            field=models.TextField(blank=True, default='', null=True, verbose_name='参数提取结果'),
        ),
        migrations.AddField(
            model_name='caseapi',
            name='response_time',
            field=models.FloatField(blank=True, null=True, verbose_name='接口响应时间'),
        ),
        migrations.AddField(
            model_name='caseapi',
            name='result_status',
            field=models.CharField(blank=True, max_length=126, null=True, verbose_name='接口执行结果'),
        ),
        migrations.AlterField(
            model_name='caseapi',
            name='check_data',
            field=models.TextField(blank=True, default='', null=True, verbose_name='期望结果'),
        ),
    ]
