# Generated by Django 2.2.17 on 2020-11-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20201113_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiresponse',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='cases.ApiManagerment', verbose_name='所属接口'),
        ),
    ]
