# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-10-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200709_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiparams',
            name='value',
            field=models.TextField(blank=True, default='', help_text='参数值', max_length=2048, null=True, verbose_name='参数值'),
        ),
    ]
