# Generated by Django 2.2.17 on 2020-11-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20201113_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casegroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='cases.CaseGroup', verbose_name='上级分组'),
        ),
    ]
