# Generated by Django 2.2.17 on 2020-11-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20201117_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=20, verbose_name='函数文件名称')),
                ('funName', models.CharField(max_length=124, verbose_name='函数名称')),
                ('content', models.TextField(verbose_name='函数内')),
                ('funcResult', models.CharField(max_length=128, verbose_name='函数返回值')),
            ],
            options={
                'verbose_name': '自定义函数',
                'verbose_name_plural': '自定义函数',
                'db_table': 'custom_func',
            },
        ),
    ]
