# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-30 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='环境名称', max_length=10, verbose_name='环境名称')),
                ('desc', models.TextField(help_text='环境描述', verbose_name='环境描述')),
                ('type', models.IntegerField(choices=[(1, '开发环境'), (2, '测试环境'), (3, '预生产环境'), (4, '生产环境')], default=1, help_text='环境类型', verbose_name='环境类型')),
                ('host', models.CharField(default='', help_text='IP/域名', max_length=126, verbose_name='IP/域名')),
                ('port', models.IntegerField(default=8080, help_text='端口', verbose_name='端口')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '可用')], default=1, help_text='环境是否可用', verbose_name='环境是否可用')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
                'db_table': 'environment_info',
            },
        ),
        migrations.CreateModel(
            name='ModelManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='模块名称')),
                ('desc', models.TextField(help_text='模块描述', verbose_name='模块描述')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
                'db_table': 'model_info',
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, default='', help_text='项目编号', max_length=16, null=True, verbose_name='项目编号')),
                ('name', models.CharField(blank=True, help_text='项目名称', max_length=20, null=True, verbose_name='项目名称')),
                ('desc', models.TextField(default='', help_text='项目描述', verbose_name='项目描述')),
                ('open_time', models.DateField(blank=True, default=datetime.datetime.now, help_text='项目开始日期', null=True, verbose_name='项目开始日期')),
                ('close_time', models.DateField(blank=True, default='', help_text='项目结束日期', null=True, verbose_name='项目结束日期')),
                ('members', models.CharField(blank=True, default='', help_text='项目成员', max_length=100, null=True, verbose_name='项目成员')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project_info',
            },
        ),
    ]
