# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-30 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmanager',
            name='model_owner',
            field=models.ForeignKey(blank=True, help_text='模块负责人', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='模块负责人'),
        ),
        migrations.AddField(
            model_name='modelmanager',
            name='parent_model',
            field=models.ForeignKey(blank=True, help_text='父模块名称', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_leverl', to='base.ModelManager', verbose_name='父模块名称'),
        ),
        migrations.AddField(
            model_name='modelmanager',
            name='project',
            field=models.ForeignKey(blank=True, help_text='项目名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ProjectManager', verbose_name='项目名称'),
        ),
    ]
