# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-27 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_remove_projectdynamic_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envmanager',
            name='status',
            field=models.IntegerField(choices=[(1, '禁用'), (2, '可用')], default=1, help_text='环境是否可用', verbose_name='环境是否可用'),
        ),
        migrations.RemoveField(
            model_name='modelmanager',
            name='model_owner',
        ),
        migrations.AddField(
            model_name='modelmanager',
            name='model_owner',
            field=models.ManyToManyField(blank=True, help_text='模块负责人', null=True, to=settings.AUTH_USER_MODEL, verbose_name='模块负责人'),
        ),
    ]
