# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-11 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200509_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envmanager',
            name='desc',
            field=models.TextField(blank=True, help_text='环境描述', null=True, verbose_name='环境描述'),
        ),
        migrations.AlterField(
            model_name='envmanager',
            name='host',
            field=models.CharField(blank=True, default='', help_text='IP/域名', max_length=126, null=True, verbose_name='IP/域名'),
        ),
        migrations.AlterField(
            model_name='envmanager',
            name='port',
            field=models.IntegerField(blank=True, default=8080, help_text='端口', null=True, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='envmanager',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, '禁用'), (2, '可用')], default=1, help_text='环境是否可用', null=True, verbose_name='环境是否可用'),
        ),
        migrations.AlterField(
            model_name='envmanager',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '开发环境'), (2, '测试环境'), (3, '预生产环境'), (4, '生产环境')], default=1, help_text='环境类型', null=True, verbose_name='环境类型'),
        ),
        migrations.AlterField(
            model_name='modelmanager',
            name='desc',
            field=models.TextField(blank=True, help_text='模块描述', null=True, verbose_name='模块描述'),
        ),
        migrations.AlterField(
            model_name='modelmanager',
            name='model_owner',
            field=models.ManyToManyField(blank=True, help_text='模块负责人', null=True, to=settings.AUTH_USER_MODEL, verbose_name='模块负责人'),
        ),
    ]
