# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-13 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sidebarinfo_useinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useinfo',
            name='menus',
        ),
        migrations.AddField(
            model_name='useinfo',
            name='menus',
            field=models.ManyToManyField(blank=True, null=True, to='users.sidebarInfo', verbose_name='导航内容'),
        ),
    ]
