# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-13 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200413_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='useinfo',
            name='role',
            field=models.CharField(default='TEST', max_length=12, verbose_name='角色'),
        ),
    ]
